### ISSUE TITLE
Parser.php throws Exception when yaml contains parameters in already quoted string

### ISSUE THREAD

**Issue by dannyvankooten** [symplify/config-transformer#24]
And contains a `:` in the string just before the parameter.

Example YAML config to replicate:

```yaml
monolog:
    handlers:
        symfony_mailer:
            type: symfony_mailer
            subject: 'Critical error on mc4wp.com: %%message%%'
```

This seems to be due to the quoting of unquoted parameter regex. Sending a PR to address this is in a minute.
